// AUTOGENERATED, DO NOT EDIT!!
package main

import (
	"fmt"
	"math"
	"math/rand"
	"time"
)

func main() {
	rand.Seed(time.Now().UTC().UnixNano())
	x := rand.Float64()
	y := rand.Float64()
	z := rand.Float64()
	a := x + sqrt(pow(z, 3)) + 99*(5*x+55)/6 + y
	fmt.Printf("formula: %f\n", a)
	fmt.Printf("parsed : %f\n", Compute(x, y, z))
}

func Compute(x, y, z float64) float64 {
	v_0 := x
	v_1 := z
	v_2 := y
	v1 := 3.000000
	v2 := pow(v_1, v1)
	v3 := sqrt(v2)
	v4 := v_0 + v3
	v5 := 99.000000
	v6 := 5.000000
	v7 := v6 * v_0
	v8 := 55.000000
	v9 := v7 + v8
	v10 := v5 * v9
	v11 := 6.000000
	v12 := v10 / v11
	v13 := v4 + v12
	v14 := v13 + v_2
	return v14
}

func sqrt(a float64) float64 {
	return math.Sqrt(a)
}

func pow(a, b float64) float64 {
	return math.Pow(a, b)
}
