// AUTOGENERATED, DO NOT EDIT!!
package main

import (
	"fmt"
	"math/rand"
)

func main() {
	x := rand.Float64()
	y := rand.Float64()
	a := 99*(5*x+55)/6 + y
	fmt.Printf("formula: %f\n", a)
	fmt.Printf("parsed : %f\n", Compute(x, y))
}

func Compute(x, y float64) float64 {
	v0 := 99.000000
	v1 := 5.000000
	v2 := x
	v3 := v1 * v2
	v4 := 55.000000
	v5 := v3 + v4
	v6 := v0 * v5
	v7 := 6.000000
	v8 := v6 / v7
	v9 := y
	v10 := v8 + v9
	return v10
}
